/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package jinternal;

import modelo.ModeloBaseDatos;

/**
 *
 * @author santoslopeztzoy
 */
public class JInternalFrameListadoBaseDatos extends javax.swing.JInternalFrame {
    
    private ModeloBaseDatos modelo;
    

    /**
     * Creates new form JInternalFrameListadoBaseDatos
     */
    public JInternalFrameListadoBaseDatos() {
        initComponents();
        setSize(600,250);
        setClosable(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelListadoBaseDatos = new javax.swing.JPanel();
        jLabelListadoBaseDatos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTablaListadoBaseDatos = new javax.swing.JTable();

        setTitle("Listado de base de datos");

        jLabelListadoBaseDatos.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabelListadoBaseDatos.setForeground(new java.awt.Color(0, 51, 255));
        jLabelListadoBaseDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelListadoBaseDatos.setText("Listado de base de datos");

        modelo = new ModeloBaseDatos();
        jTableTablaListadoBaseDatos.setModel(modelo);
        jScrollPane1.setViewportView(jTableTablaListadoBaseDatos);

        javax.swing.GroupLayout jPanelListadoBaseDatosLayout = new javax.swing.GroupLayout(jPanelListadoBaseDatos);
        jPanelListadoBaseDatos.setLayout(jPanelListadoBaseDatosLayout);
        jPanelListadoBaseDatosLayout.setHorizontalGroup(
            jPanelListadoBaseDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelListadoBaseDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanelListadoBaseDatosLayout.setVerticalGroup(
            jPanelListadoBaseDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListadoBaseDatosLayout.createSequentialGroup()
                .addComponent(jLabelListadoBaseDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelListadoBaseDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelListadoBaseDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelListadoBaseDatos;
    private javax.swing.JPanel jPanelListadoBaseDatos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTablaListadoBaseDatos;
    // End of variables declaration//GEN-END:variables
}
